<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class News extends \AppBundle\Entity\News implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'photoFile', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'ndate', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsdesc', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsType', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'idNews', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'titleEn', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'dogsPhotos', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'videos', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsdescEn'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'photoFile', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'ndate', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsdesc', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsType', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'idNews', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'titleEn', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'dogsPhotos', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'videos', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsdescEn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (News $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPhotoFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoFile', [$image]);

        return parent::setPhotoFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoFile', []);

        return parent::getPhotoFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getDogsPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogsPhotos', []);

        return parent::getDogsPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function getVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideos', []);

        return parent::getVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setDogsPhotos($dogsPhotos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogsPhotos', [$dogsPhotos]);

        return parent::setDogsPhotos($dogsPhotos);
    }

    /**
     * {@inheritDoc}
     */
    public function setVideos($videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideos', [$videos]);

        return parent::setVideos($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVideos(\AppBundle\Entity\Videos $video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVideos', [$video]);

        return parent::removeVideos($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleEn', []);

        return parent::getTitleEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsdescEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsdescEn', []);

        return parent::getNewsdescEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleEn($titleEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleEn', [$titleEn]);

        return parent::setTitleEn($titleEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsdescEn($newsdescEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsdescEn', [$newsdescEn]);

        return parent::setNewsdescEn($newsdescEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setNdate($ndate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNdate', [$ndate]);

        return parent::setNdate($ndate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNdate', []);

        return parent::getNdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsdesc($newsdesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsdesc', [$newsdesc]);

        return parent::setNewsdesc($newsdesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsdesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsdesc', []);

        return parent::getNewsdesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsType($newsType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsType', [$newsType]);

        return parent::setNewsType($newsType);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsType', []);

        return parent::getNewsType();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNews()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdNews();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNews', []);

        return parent::getIdNews();
    }

}
