<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Litters extends \AppBundle\Entity\Litters implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'ldate', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'idLitters', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'mother', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'father', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'dogs'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'ldate', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'idLitters', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'mother', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'father', '' . "\0" . 'AppBundle\\Entity\\Litters' . "\0" . 'dogs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Litters $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setLdate($ldate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLdate', [$ldate]);

        return parent::setLdate($ldate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLdate', []);

        return parent::getLdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLitters()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLitters();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLitters', []);

        return parent::getIdLitters();
    }

    /**
     * {@inheritDoc}
     */
    public function setMother(\AppBundle\Entity\Dogs $Mother = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMother', [$Mother]);

        return parent::setMother($Mother);
    }

    /**
     * {@inheritDoc}
     */
    public function getMother()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMother', []);

        return parent::getMother();
    }

    /**
     * {@inheritDoc}
     */
    public function setFather(\AppBundle\Entity\Dogs $father = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFather', [$father]);

        return parent::setFather($father);
    }

    /**
     * {@inheritDoc}
     */
    public function getFather()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFather', []);

        return parent::getFather();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDogs(\Doctrine\Common\Collections\ArrayCollection $dogs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogs', [$dogs]);

        return parent::setDogs($dogs);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogs', []);

        return parent::getDogs();
    }

    /**
     * {@inheritDoc}
     */
    public function addDog(\AppBundle\Entity\Dogs $dog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDog', [$dog]);

        return parent::addDog($dog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDog(\AppBundle\Entity\Dogs $dog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDog', [$dog]);

        return parent::removeDog($dog);
    }

}
