<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nursery extends \AppBundle\Entity\Nursery implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'photoFile', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'nameNur', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'nameNurEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'bdate', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'owner', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'ownerEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'adress', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'adressEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'phone', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'cellphone', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'idNursery', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'about', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'aboutEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'site'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'photoFile', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'nameNur', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'nameNurEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'bdate', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'owner', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'ownerEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'adress', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'adressEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'phone', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'cellphone', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'idNursery', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'about', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'aboutEn', '' . "\0" . 'AppBundle\\Entity\\Nursery' . "\0" . 'site'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nursery $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPhotoFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoFile', [$image]);

        return parent::setPhotoFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoFile', []);

        return parent::getPhotoFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getAboutEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAboutEn', []);

        return parent::getAboutEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setAboutEn($aboutEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAboutEn', [$aboutEn]);

        return parent::setAboutEn($aboutEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbout', []);

        return parent::getAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbout($about)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbout', [$about]);

        return parent::setAbout($about);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', []);

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', [$site]);

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function setNameNur($nameNur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameNur', [$nameNur]);

        return parent::setNameNur($nameNur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameNur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameNur', []);

        return parent::getNameNur();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameNurEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameNurEn', []);

        return parent::getNameNurEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameNurEn($nameNurEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameNurEn', [$nameNurEn]);

        return parent::setNameNurEn($nameNurEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setBdate($bdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBdate', [$bdate]);

        return parent::setBdate($bdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBdate', []);

        return parent::getBdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner($owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnerEn', []);

        return parent::getOwnerEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerEn($ownerEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnerEn', [$ownerEn]);

        return parent::setOwnerEn($ownerEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress($adress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressEn', []);

        return parent::getAdressEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressEn($adressEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressEn', [$adressEn]);

        return parent::setAdressEn($adressEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setCellphone($cellphone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCellphone', [$cellphone]);

        return parent::setCellphone($cellphone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCellphone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCellphone', []);

        return parent::getCellphone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNursery()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdNursery();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNursery', []);

        return parent::getIdNursery();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
