<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dogs extends \AppBundle\Entity\Dogs implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'photoFile', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'nameEn', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'bdate', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'descriptionEn', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'quality', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'sex', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'state', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'dogsPhotos', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'videos', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'dogTitles', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'dogVaccinations', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'idDogs', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'nursery', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'litters'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'photoFile', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'nameEn', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'bdate', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'descriptionEn', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'photo', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'quality', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'sex', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'state', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'dogsPhotos', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'videos', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'dogTitles', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'dogVaccinations', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'idDogs', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'nursery', '' . "\0" . 'AppBundle\\Entity\\Dogs' . "\0" . 'litters'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dogs $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPhotoFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoFile', [$image]);

        return parent::setPhotoFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoFile', []);

        return parent::getPhotoFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameEn', []);

        return parent::getNameEn();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionEn', []);

        return parent::getDescriptionEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameEn($nameEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameEn', [$nameEn]);

        return parent::setNameEn($nameEn);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionEn($descriptionEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionEn', [$descriptionEn]);

        return parent::setDescriptionEn($descriptionEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getDogsPhotos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogsPhotos', []);

        return parent::getDogsPhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function getVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideos', []);

        return parent::getVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function getDogVaccinations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogVaccinations', []);

        return parent::getDogVaccinations();
    }

    /**
     * {@inheritDoc}
     */
    public function setDogsPhotos($dogsPhotos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogsPhotos', [$dogsPhotos]);

        return parent::setDogsPhotos($dogsPhotos);
    }

    /**
     * {@inheritDoc}
     */
    public function setDogVaccinations($dogVaccinations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogVaccinations', [$dogVaccinations]);

        return parent::setDogVaccinations($dogVaccinations);
    }

    /**
     * {@inheritDoc}
     */
    public function setDogTitles(array $dogTitles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDogTitles', [$dogTitles]);

        return parent::setDogTitles($dogTitles);
    }

    /**
     * {@inheritDoc}
     */
    public function setVideos($videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideos', [$videos]);

        return parent::setVideos($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getDogTitles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDogTitles', []);

        return parent::getDogTitles();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function setLitters($litters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLitters', [$litters]);

        return parent::setLitters($litters);
    }

    /**
     * {@inheritDoc}
     */
    public function getLitters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLitters', []);

        return parent::getLitters();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBdate($bdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBdate', [$bdate]);

        return parent::setBdate($bdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBdate', []);

        return parent::getBdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuality($quality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuality', [$quality]);

        return parent::setQuality($quality);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuality', []);

        return parent::getQuality();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', [$sex]);

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', []);

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDogs()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdDogs();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDogs', []);

        return parent::getIdDogs();
    }

    /**
     * {@inheritDoc}
     */
    public function setNursery(\AppBundle\Entity\Nursery $nursery = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNursery', [$nursery]);

        return parent::setNursery($nursery);
    }

    /**
     * {@inheritDoc}
     */
    public function getNursery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNursery', []);

        return parent::getNursery();
    }

    /**
     * {@inheritDoc}
     */
    public function addDogtitle(\AppBundle\Entity\DogTitles $dogtitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogtitle', [$dogtitle]);

        return parent::addDogtitle($dogtitle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogtitle(\AppBundle\Entity\DogTitles $dogtitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogtitle', [$dogtitle]);

        return parent::removeDogtitle($dogtitle);
    }

    /**
     * {@inheritDoc}
     */
    public function addDogVaccination(\AppBundle\Entity\DogVaccinations $dogVaccinations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogVaccination', [$dogVaccinations]);

        return parent::addDogVaccination($dogVaccinations);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogVaccination(\AppBundle\Entity\DogVaccinations $dogVaccination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogVaccination', [$dogVaccination]);

        return parent::removeDogVaccination($dogVaccination);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDogsphoto(\AppBundle\Entity\DogsPhotos $dogphoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDogsphoto', [$dogphoto]);

        return parent::removeDogsphoto($dogphoto);
    }

    /**
     * {@inheritDoc}
     */
    public function addDogsphoto(\AppBundle\Entity\DogsPhotos $dogphoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDogsphoto', [$dogphoto]);

        return parent::addDogsphoto($dogphoto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVideo(\AppBundle\Entity\Videos $videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVideo', [$videos]);

        return parent::removeVideo($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function addVideo(\AppBundle\Entity\Videos $videos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVideo', [$videos]);

        return parent::addVideo($videos);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
